<a href="https://colab.research.google.com/github/Saab1710/Saab1710/blob/main/Seminar_Week_7.6_2025_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

np.linalg.norm is a function from the NumPy library that calculates the vector norm or the magnitude of a given vector. When we subtract two points point1 and point2, we get a vector that represents the direction and magnitude from point2 to point1. The function np.linalg.norm computes the magnitude of this vector, which is the distance between the two points in Euclidean space.

In [1]:
#Solution- Q1
import numpy as np

# initializing points in
# numpy arrays
point1 = np.array((4, 9, 1))
point2 = np.array((2, 3, 7))

# calculating Euclidean distance
# using linalg.norm()
dist = np.linalg.norm(point1 - point2)

# printing Euclidean distance
print(dist)


8.717797887081348


In [7]:
import numpy as np

# Initializing points in numpy arrays
point1 = np.array((4, 9, 1))
point2 = np.array((2, 3, 7))

# Calculating squared difference
squared_diff = np.square(point1 - point2)

# Summing the squared differences and taking the square root
dist = np.sqrt(np.sum(squared_diff))

# Printing the Euclidean distance
print(dist)


9.0


In [3]:
#Solution- Q2
import numpy as np
x1 = np.array(['Big', 'Mongo'])
x2 = np.array(['Data', 'DB'])
#print('Array1:')
#print(x1)
#print('Array2:')
#print(x2)
new_array = np.char.add(x1, x2)
print('new array:')
print(new_array)


new array:
['BigData' 'MongoDB']


In this example, x1 is an array of strings ['Big', 'Mongo'], and x2 is an array of strings ['Data', 'DB']. The np.char.add function concatenates the two arrays element-wise as strings, resulting in a new array ['BigData', 'MongoDB'].

In [4]:
#Solution- Q3
#Here we’re creating a new array with a descending range: [10  9  8  7  6  5  4  3  2  1] and
#adding it to [ 1  2  3  4  5  6  7  8  9 10], so we get an array with the values [11 11 11 11 11 11 11 11 11 11].
one_dim= np.array([1,2,3,4,5,6,7,8,9,10])
print(one_dim)
print(np.arange(10, 0, -1))
print(one_dim + np.arange(10, 0, -1))


[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]
[11 11 11 11 11 11 11 11 11 11]


In [5]:
# What is the result of array_one > 2 ?


print(one_dim > 2)


[False False  True  True  True  True  True  True  True  True]


In [6]:
#Solution- Q4
import numpy as np

arr1= np.array([1,2,3,5,7])
print(np.max(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.sum(arr1))
print(np.average(arr1))
print(np.std(arr1))


7
1
7
18
3.6
2.1540659228538015
